// <auto-generated />
using EOkul.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EOkul.Migrations
{
    [DbContext(typeof(OkulDbContext))]
    partial class OkulDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EOkul.Model.Ders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasDefaultValue("Adi");

                    b.Property<double>("BiyolojiOrt")
                        .HasColumnType("float");

                    b.Property<double>("FizikOrt")
                        .HasColumnType("float");

                    b.Property<double>("KimyaOrt")
                        .HasColumnType("float");

                    b.Property<double>("MatOrt")
                        .HasColumnType("float");

                    b.Property<string>("Numarasi")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasDefaultValue("Numarasi");

                    b.Property<double>("TurkceOrt")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("tblDers", (string)null);
                });

            modelBuilder.Entity("EOkul.Model.Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciId"));

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasDefaultValue("KullaniciAdi");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasDefaultValue("Sifre");

                    b.HasKey("KullaniciId");

                    b.ToTable("tblKullanici", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
